### ISSUE TITLE
move this repo??

### ISSUE THREAD

**Issue by philschatz** [Connexions/cnx-tools#2]
Woah, I didn't realize this existed!

Can we move it to github.com/openstax and rename it to `book-tools`?

This would have a couple advantages:

1. house the API documentation for cnx.org : https://github.com/openstax/napkin-notes/pull/73
1. house the Issues which are currently on cnx-recipes

/cc @kerwinso @edwoodward @reedstrm @pumazi

**Comment by kerwinso** [comment]
Seems like @brittweinstein should be the owner of the cnx-tools repo, since she's the product owner for Content Production Tools. (She is also not a member of Rhaptos, so I'm not sure she can comment directly in this issue.) She may want to call it something other than `book-tools` since we already use that name internally to encompass a number of projects.

**Comment by brittweinstein** [comment]
@philschatz are you able to make me a member of Rhaptos? That'd be very helpful to get this there as well...let's rename "content-production-tools"?

**Comment by philschatz** [comment]
@brittweinstein is it ok if you are added after a new home is decided? 

RE repo "ownership", in the openstax org all users have write access to all repos (except some deployment repos).

I suggested `book-tools` because the name was similar but it could be a separate repo (Aside: I'm not a fan of repo splintering)

**Comment by edwoodward** [comment]
@philschatz This was created to house tools related to cnx data. I'm not sure it should be used as a catch all for issues and documentation. Maybe a new repo should be created for that. I have no problem with moving the repo to OpenStax

**Comment by edwoodward** [comment]
Moved it to Connexions and it should be moved to OpenStax
